-- Exploratory Data Analysis (EDA) on Marketing Performance

-- 1. Total number of marketing campaigns
SELECT COUNT(DISTINCT campaign_id) AS total_campaigns FROM marketing_data;

-- 2. Total impressions, clicks, and conversions
SELECT SUM(impressions) AS total_impressions, 
       SUM(clicks) AS total_clicks, 
       SUM(conversions) AS total_conversions
FROM marketing_data;

-- 3. Average Click-Through Rate (CTR) by marketing channel
SELECT channel, 
       AVG(clicks * 100.0 / impressions) AS avg_ctr
FROM marketing_data
GROUP BY channel;

-- 4. Campaigns with the highest and lowest conversion rates
SELECT campaign_id, (SUM(conversions) * 100.0 / SUM(clicks)) AS conversion_rate
FROM marketing_data
GROUP BY campaign_id
ORDER BY conversion_rate DESC
LIMIT 5;

-- 5. Total revenue generated by each product
SELECT product_name, SUM(revenue) AS total_revenue
FROM marketing_data
GROUP BY product_name
ORDER BY total_revenue DESC;

-- 6. Top-performing regions by revenue
SELECT region, SUM(revenue) AS total_revenue
FROM marketing_data
GROUP BY region
ORDER BY total_revenue DESC;

-- 7. Total spend and return on investment (ROI) per channel
SELECT channel, SUM(spend) AS total_spend, 
       SUM(revenue) / NULLIF(SUM(spend), 0) AS roi
FROM marketing_data
GROUP BY channel
ORDER BY roi DESC;

-- 8. Month-over-month revenue growth trend
SELECT DATE_TRUNC('month', campaign_date) AS month, 
       SUM(revenue) AS monthly_revenue
FROM marketing_data
GROUP BY month
ORDER BY month;

-- 9. Products with the highest customer engagement (based on clicks)
SELECT product_name, SUM(clicks) AS total_clicks
FROM marketing_data
GROUP BY product_name
ORDER BY total_clicks DESC;

-- 10. Average CPC (Cost Per Click) per marketing channel
SELECT channel, AVG(spend / NULLIF(clicks, 0)) AS avg_cpc
FROM marketing_data
GROUP BY channel;
